### ISSUE TITLE
synchronous loadConfig

### ISSUE THREAD

**Issue by DetachHead** [launchcodedev/app-config#146]
it would be great if you could load the config without requiring an IIFE and a call to the `loadConfig` function at runtime.

something like `node -r app-config/register` for example.

**Comment by joelgallant** [comment]
Thanks for the feedback!

I believe that this would be something solved by https://v8.dev/features/top-level-await This is available in Node 14+, when using a `"type": "module"` package.

Unfortunately, this isn't possible to do with a `--require` because `loadConfig` is async, at least as far as I know. (it would lead to race conditions otherwise)

**Comment by joelgallant** [comment]
@DetachHead does this solve your use case?

**Comment by DetachHead** [comment]
i tried updating our project to esmodules, but wasn't able to get it working with jest. seems their support for esmodules is experimental and it wouldn't work no matter what i tried.

**Comment by joelgallant** [comment]
Hm, yeah the Node ecosystem will still take a while to get there 100%.

Is https://app-config.dev/guide/testing/jest.html enough? It might require duplication unfortunately, but it's the best way I know of at the moment.

**Comment by DetachHead** [comment]
Yeah mocking it worked for our use case, though as mentioned in #100 that's not really ideal

**Comment by joelgallant** [comment]
Okay, thanks for the feedback! I agree with the conclusion there, wanted to make sure there wasn't an issue I could help with more quickly.

Moved this feature request to #152
