### ISSUE TITLE
Towards App Config CLI Parity w/ Node.js API

### ISSUE THREAD

**Issue by joelgallant** [launchcodedev/app-config#20]
- [x] Environment Variable Names
- [x] Environment Override (alternative to setting `APP_CONFIG_ENV`)
- [x] File Name Base Name

Meta file settings:
- [x] Parsing extensions
- [ ] Environment type variable name(s)  - `APP_CONFIG_ENV`, `NODE_ENV`, etc.
- [ ] Environment aliases

**Comment by joelgallant** [comment]
@gregnr's suggestion here was adding options here to the meta file, so that Node.js and CLI act the same way (consistently, as well). Node.js options would be treated as overrides. (meaning order of precedent is CLI arg / Node.js arg, meta file option, default option)

**Comment by joelgallant** [comment]
Lookup mechanism for parsing extensions - this is essentially akin to plugin systems like babel. Could use the NPM module name and use default export. Could be a js file. Would want a special syntax or keys for built-in extensions. Note that this requires loadMeta in loadConfig, which isn't necessary atm. I still think that this can be done without breaking changes.

**Comment by joelgallant** [comment]
Meta file:
- [ ] Parsing extensions
- [ ] Environment variable names
- [ ] File name base

**Comment by joelgallant** [comment]
This is mostly a done deal. I think that other loadConfig options are a bit out of scope for the meta file, imo.

**Comment by gregnr** [comment]
@joelgallant Coming across a situation in React Native where we may want the ability to configure environment variable names within the meta file after all.

## Scenario

With our React Native plugin, `app-config` works within a dev environment, but up until now has never been tested for release builds. How do you specify the `app-config` environment when building a `qa`, `staging`, `prod` release, particularly for iOS?

We started by specifying `NODE_ENV` before running `xcodebuild`, ie:

```bash
NODE_ENV=qa xcodebuild...
```

This unfortunately did not work since RN seems to overwrite this somewhere downstream. We instead used `APP_CONFIG_ENV` which thankfully worked:

```bash
APP_CONFIG_ENV=qa xcodebuild...
```

## Proposal
The above gets us going, but I feel like this could be better. For example, building from the Xcode IDE directly will never work, since Xcode of course has no concept of `APP_CONFIG_ENV`. Also as you may know Xcode creates 2 configurations by default for an iOS project: `Debug` and `Release`. You can set different bundle identifiers per configuration, which is ideal for different environments.

On that note we're trying to come up with the best, most ergonomic way to marry iOS Xcode "configurations" with `app-config` environments. . We're considering replacing the two default configurations with a configuration for each environment, eg `dev`, `qa`, `staging`, `prod`. It would be nice to somehow use Xcode configurations to determine environment within `app-config`.

Turns out when Metro runs, Xcode exposes the current configuration via the `${CONFIGURATION}` environment variable. If we could tell `app-config` to use `${CONFIGURATION}` instead of `${APP_CONFIG_ENV}`, that would solve our problem. Unfortunately Metro doesn't make it easy to configuration transformers, so we have no good way to customize the `options.environmentVariableName` from the Node API. If we could instead specify this in the `.app-config.meta.yml` file, this would work.

While we're at it, it would also be nice to specify `options.environmentAliases` inside the meta file so that people have the option to use other names/casing in their Xcode configurations, eg:

```yaml
environmentAliases:
  Debug: 'development'
  Release: 'production'
```
or

```yaml
environmentAliases:
  Dev: 'development'
  QA: 'qa'
  Staging: 'staging'
  Prod: 'production'
```

Thoughts?

**Comment by joelgallant** [comment]
Agree entirely, that makes sense to me. See #98.

On the side, I think XCode allows setting environment variables, I remember us doing that in SOL iirc.
